name: BuildAndPack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: |
          cmake -E remove_directory build
          cmake -E make_directory build
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Pack
        run: |
          cd build
          cpack

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: AGHPresenter-Win64
          path: build/AGHPresenter-1.0-win64.zip
