name: BuildAndPack

env:
  CONAN_REVISIONS_ENABLED: 1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      MacOS:
        description: 'Build MacOS?'     
        required: true
        default: 'false'
      Linux:
        description: 'Build Linux?'     
        required: true
        default: 'false'

jobs:
  Win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: |
          cmake -E remove_directory build
          cmake -E make_directory build
          cd build
          cmake .. -G "Visual Studio 16 2019"
          cmake --build . --config Release

      - name: Pack
        run: |
          cd build
          cpack

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: AGHPresenter-Win64
          path: build/AGHPresenter-*.*-*.zip

  Mac:
    runs-on: macos-latest
    if: github.github.event.inputs.MacOS == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build
        run: |
          cmake -E remove_directory build
          cmake -E make_directory build
          cd build
          cmake .. -G "Xcode"
          cmake --build . --config Release

      - name: Pack
        run: |
          cd build
          cpack

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: AGHPresenter-MacOS
          path: build/AGHPresenter-*.*-*.zip

  Lnx:
    runs-on: ubuntu-latest
    if:  github.github.event.inputs.Linux == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install linux packages
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install -y libgl1-mesa-dev
          sudo apt-get install -y xorg-dev
          sudo apt-get install -y libxcb-render-util0-dev
          sudo apt-get install -y libxcb-xkb-dev
          sudo apt-get install -y libxcb-icccm4-dev
          sudo apt-get install -y libxcb-image0-dev
          sudo apt-get install -y libxcb-keysyms1-dev
          sudo apt-get install -y libxcb-randr0-dev
          sudo apt-get install -y libxcb-shape0-dev
          sudo apt-get install -y libxcb-sync-dev
          sudo apt-get install -y libxcb-xfixes0-dev
          sudo apt-get install -y libxcb-xinerama0-dev
          sudo apt-get install -y xkb-data
          sudo apt-get install -y libxcb-util-dev

      - name: Build
        run: |
          cmake -E remove_directory build
          cmake -E make_directory build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      - name: Pack
        run: |
          cd build
          cpack

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: AGHPresenter-Linux
          path: build/AGHPresenter-*.*-*.zip

